version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Asus123*
      MYSQL_DATABASE: customerfinancedata
    networks:
      - app-network

  app:
    image: tuimagen/appfinance:latest
    container_name: app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/customerfinancedata
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Asus123*
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge